version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: comet-postgres
    environment:
      POSTGRES_DB: comet_devops
      POSTGRES_USER: comet_user
      POSTGRES_PASSWORD: comet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - comet-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: comet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - comet-network

  # InfluxDB for Metrics
  influxdb:
    image: influxdb:2.7-alpine
    container_name: comet-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123456
      DOCKER_INFLUXDB_INIT_ORG: comet
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - comet-network

  # Elasticsearch for Logs and Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: comet-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - comet-network

  # Kibana for Log Visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: comet-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - comet-network

  # RabbitMQ for Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: comet-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: comet
      RABBITMQ_DEFAULT_PASS: comet123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - comet-network

volumes:
  postgres_data:
  redis_data:
  influxdb_data:
  influxdb_config:
  elasticsearch_data:
  rabbitmq_data:

networks:
  comet-network:
    driver: bridge